# Generated by Django 6.0.6 on 2026-06-20 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Ingreso por compra'), ('SALE_OUT', 'Salida por venta'), ('TRANSFER_OUT', 'Salida por transferencia'), ('TRANSFER_IN', 'Ingreso por transferencia'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo'), ('RETURN_IN', 'Ingreso por devolucion')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference_type', models.CharField(max_length=60)),
                ('reference_id', models.UUIDField()),
                ('document_number', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('counterpart_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.warehouse')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='tenancy.warehouse')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.lot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='tenancy.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['company', 'expiry_date', 'is_blocked'], name='inventory_l_company_c64000_idx'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('company', 'variant', 'batch_number', 'expiry_date'), name='uq_lot_company_variant_batch_expiry', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['company', 'warehouse', 'variant', 'created_at'], name='inventory_i_company_c05f62_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['company', 'reference_type', 'reference_id'], name='inventory_i_company_a9bf56_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['company', 'warehouse', 'variant'], name='inventory_s_company_4117b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['company', 'warehouse', 'quantity'], name='inventory_s_company_e5896f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'variant', 'lot'), name='uq_stock_company_warehouse_variant_lot', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ck_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='ck_stock_reserved_non_negative'),
        ),
    ]
