# Generated by Django 6.0.6 on 2026-06-20 23:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_purchase_data(apps, schema_editor):
    Purchase = apps.get_model("purchases", "Purchase")
    PurchaseItem = apps.get_model("purchases", "PurchaseItem")
    Purchase.objects.filter(status="RECEIVED").update(status="CONFIRMED")
    for item in PurchaseItem.objects.all().iterator():
        item.pack_quantity = item.quantity
        item.purchase_factor = 1
        item.purchase_pack_price = item.unit_cost
        item.save(update_fields=["pack_quantity", "purchase_factor", "purchase_pack_price"])


def restore_purchase_data(apps, schema_editor):
    apps.get_model("purchases", "Purchase").objects.filter(status="CONFIRMED").update(status="RECEIVED")


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashmovement_movement_type_cashcount'),
        ('catalog', '0002_activeingredient_productwarehouselocation_and_more'),
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_paid', to='cash.cashsession'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_condition',
            field=models.CharField(choices=[('CASH', 'Contado'), ('CREDIT', 'Credito')], default='CASH', max_length=16),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=16),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='pack_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=16),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_pack_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=16),
        ),
        migrations.RunPython(migrate_purchase_data, restore_purchase_data),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('pack_quantity__gt', 0)), name='ck_purchase_pack_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_factor__gt', 0)), name='ck_purchase_factor_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_pack_price__gte', 0)), name='ck_purchase_pack_price_non_negative'),
        ),
    ]
