export type ModuleAction = {
  label: string;
  icon: string;
  className: string;
  intent?: "create" | "export" | "print" | "sync" | "search" | "edit";
};

export type ModuleScreen = {
  title: string;
  section: string;
  current: string;
  tabs?: string[];
  tabRoutes?: Record<string, string>;
  actions: ModuleAction[];
  columns: string[];
  rows: string[][];
  formFields?: string[];
};

const defaultActions: ModuleAction[] = [
  { label: "Nuevo", icon: "", className: "", intent: "create" },
  { label: "Excel", icon: "", className: "", intent: "export" },
  { label: "PDF", icon: "", className: "", intent: "print" },
];

export const moduleScreens: Record<string, ModuleScreen> = {
  "/inicio": {
    title: "Inicio",
    section: "Panel",
    current: "Inicio",
    actions: [],
    columns: ["Indicador", "Valor", "Estado"],
    rows: [
      ["Productos activos", "0", "Pendiente API"],
      ["Ventas del dia", "0.00", "Pendiente API"],
      ["Stock minimo", "0", "Pendiente API"],
      ["Proximos a vencer", "0", "Pendiente API"],
    ],
    formFields: ["Indicador", "Valor", "Estado"],
  },
  "/venta": {
    title: "Comprobante Electronico",
    section: "Venta",
    current: "Comprobante",
    tabs: ["Comprobantes", "Nuevo", "Notas de credito", "Arqueo"],
    actions: [
      { label: "Nuevo Comprobante", icon: "", className: "", intent: "create" },
      { label: "Consultar", icon: "", className: "", intent: "search" },
      { label: "PDF", icon: "", className: "", intent: "print" },
    ],
    columns: ["#", "Fecha", "Comprobante", "Cliente", "Total", "Estado", "Acciones"],
    rows: [["1", "-", "B001-00000000", "CLIENTES VARIOS", "0.00", "Pendiente API", ""]],
    formFields: ["Fecha", "Comprobante", "Serie", "Cliente", "Documento", "Producto", "Cantidad", "Precio", "Total", "Medio de Pago"],
  },
  "/nventa": {
    title: "Notas de Venta",
    section: "Venta",
    current: "Notas de Venta",
    tabs: ["Notas", "Nueva Nota", "Consulta"],
    actions: [
      { label: "Nueva Nota", icon: "", className: "", intent: "create" },
      { label: "PDF", icon: "", className: "", intent: "print" },
    ],
    columns: ["#", "Fecha", "Numero", "Cliente", "Total", "Estado", "Acciones"],
    rows: [["1", "-", "NV-000000", "CLIENTES VARIOS", "0.00", "Pendiente API", ""]],
    formFields: ["Fecha", "Numero", "Cliente", "Producto", "Cantidad", "Precio", "Total", "Medio de Pago"],
  },
  "/cotizacion": {
    title: "Cotizaciones de Venta",
    section: "Venta",
    current: "Cotizaciones",
    actions: [
      { label: "Nueva Cotizacion", icon: "", className: "", intent: "create" },
      { label: "PDF", icon: "", className: "", intent: "print" },
    ],
    columns: ["#", "Fecha", "Numero", "Cliente", "Total", "Estado", "Acciones"],
    rows: [["1", "-", "COT-000000", "CLIENTES VARIOS", "0.00", "Pendiente API", ""]],
    formFields: ["Fecha", "Numero", "Cliente", "Producto", "Cantidad", "Precio", "Total", "Validez"],
  },
  "/despacho": {
    title: "Guia de Remision",
    section: "Venta",
    current: "Despacho",
    actions: defaultActions,
    columns: ["#", "Fecha", "Guia", "Destinatario", "Motivo", "Estado", "Acciones"],
    rows: [["1", "-", "T001-000000", "-", "Venta", "Pendiente API", ""]],
    formFields: ["Fecha", "Guia", "Destinatario", "Direccion Llegada", "Transportista", "Placa", "Motivo", "Estado"],
  },
  "/cliente": {
    title: "Clientes",
    section: "Venta",
    current: "Cliente",
    actions: [
      { label: "Nuevo Cliente", icon: "", className: "", intent: "create" },
      { label: "Consultar Documento", icon: "", className: "", intent: "search" },
    ],
    columns: ["#", "Documento", "Nombres", "Direccion", "Telefono", "Puntos", "Acciones"],
    rows: [["1", "00000000", "CLIENTES VARIOS", "-", "-", "0", ""]],
    formFields: ["Tipo Documento", "Documento", "Nombres", "Direccion", "Telefono", "Correo", "Departamento", "Provincia", "Distrito"],
  },
  "/atributo": {
    title: "Atributo Producto",
    section: "Almacen",
    current: "Atributos",
    tabs: ["Categoria", "Laboratorio", "Principio Activo", "Accion Terapeutica", "Ubicacion"],
    actions: [{ label: "Nuevo Atributo", icon: "", className: "" }],
    columns: ["#", "Descripcion", "Estado", "Acciones"],
    rows: [["1", "GENERAL", "Activo", ""]],
    formFields: ["Tipo", "Descripcion", "Estado"],
  },
  "/bonificacion": {
    title: "Bonificados",
    section: "Almacen",
    current: "Bonificaciones",
    actions: [{ label: "Nuevas Bonificaciones", icon: "", className: "" }],
    columns: ["#", "Periodo", "Producto", "Cantidad", "Bonificado", "Acciones"],
    rows: [["1", "-", "-", "0", "0", ""]],
    formFields: ["Periodo", "Producto", "Cantidad", "Producto Bonificado", "Cantidad Bonificada"],
  },
  "/servicio": {
    title: "Servicios",
    section: "Almacen",
    current: "Servicios",
    actions: [{ label: "Nuevo Servicio", icon: "", className: "" }],
    columns: ["#", "Descripcion", "Precio", "Estado", "Acciones"],
    rows: [["1", "SERVICIO GENERAL", "0.00", "Activo", ""]],
    formFields: ["Descripcion", "Precio", "Estado"],
  },
  "/producto": {
    title: "Productos",
    section: "Almacen",
    current: "Productos",
    tabs: ["Activos", "Inactivos", "Stock vs Cantidad"],
    tabRoutes: {
      Activos: "/producto",
      Inactivos: "/producto/inactivos",
      "Stock vs Cantidad": "/producto/deficit",
    },
    actions: [
      { label: "Nuevo Producto", icon: "", className: "", intent: "create" },
      { label: "Actualizar Precios", icon: "", className: "", intent: "edit" },
      { label: "Importar Excel", icon: "", className: "", intent: "export" },
      { label: "Actualizar Inventario", icon: "", className: "", intent: "sync" },
    ],
    columns: ["#", "Producto", "Laboratorio", "Stock", "P. Compra", "P. Venta", "Acciones"],
    rows: [["1", "Producto de ejemplo", "-", "0", "0.00", "0.00", ""]],
    formFields: [
      "Categoria",
      "Laboratorio",
      "Codigo Barra",
      "R. Sanitario",
      "Codigo Digemid",
      "Descripcion",
      "Tipo Afectacion",
      "Stock Minimo",
      "Ubicacion",
      "Lote",
      "P. Compra",
      "Factor Unidad",
      "P. Venta",
      "Factor Blister",
      "P. Blister",
      "Factor Caja",
      "P. Caja",
      "Principio Activo",
      "Accion Terapeutica",
      "Puntos",
      "Informacion",
    ],
  },
  "/inventario": {
    title: "Actualizar Inventario",
    section: "Almacen",
    current: "Inventario",
    actions: [
      { label: "Nuevo Actualizar", icon: "", className: "" },
      { label: "Actualizar Excel", icon: "", className: "" },
    ],
    columns: ["#", "Fecha", "Numero", "Usuario", "Observacion", "Estado", "Acciones"],
    rows: [["1", "-", "INV-000000", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha", "Numero", "Producto", "Stock Fisico", "Costo", "Observacion"],
  },
  "/compra": {
    title: "Compra Mercaderia",
    section: "Compra",
    current: "Compra",
    actions: [
      { label: "Nueva Compra", icon: "", className: "" },
      { label: "Importar", icon: "", className: "" },
    ],
    columns: ["#", "Fecha", "Documento", "Proveedor", "Total", "Estado", "Acciones"],
    rows: [["1", "-", "F001-000000", "-", "0.00", "Pendiente API", ""]],
    formFields: ["Fecha", "Tipo Documento", "Serie", "Numero", "Proveedor", "Producto", "Cantidad", "Costo", "Total"],
  },
  "/solicitud": {
    title: "Solicitudes de Compra",
    section: "Compra",
    current: "Solicitudes",
    actions: [{ label: "Nueva Solicitud", icon: "", className: "" }],
    columns: ["#", "Fecha", "Numero", "Usuario", "Estado", "Acciones"],
    rows: [["1", "-", "SOL-000000", "-", "Pendiente API", ""]],
    formFields: ["Fecha", "Numero", "Proveedor", "Producto", "Cantidad", "Observacion"],
  },
  "/proveedor": {
    title: "Proveedores",
    section: "Compra",
    current: "Proveedor",
    actions: [{ label: "Nuevo Proveedor", icon: "", className: "" }],
    columns: ["#", "Documento", "Nombres", "Direccion", "Telefono", "Acciones"],
    rows: [["1", "00000000000", "PROVEEDOR GENERAL", "-", "-", ""]],
    formFields: ["Tipo Documento", "Documento", "Nombres", "Direccion", "Telefono", "Correo"],
  },
  "/caja": {
    title: "Arqueo de Caja",
    section: "Caja",
    current: "Arqueo",
    tabs: ["Arqueos", "Medios de Pago"],
    tabRoutes: {
      Arqueos: "/caja",
      "Medios de Pago": "/caja/mpago",
    },
    actions: [{ label: "Nuevo Arqueo", icon: "", className: "" }],
    columns: ["#", "Fecha Apertura", "Usuario", "Inicial", "Ingreso", "Salida", "Estado", "Acciones"],
    rows: [["1", "-", "-", "0.00", "0.00", "0.00", "Pendiente API", ""]],
    formFields: ["Fecha Apertura", "Usuario", "Monto Inicial", "Observacion", "Estado"],
  },
  "/cobrar": {
    title: "Cuentas por Cobrar",
    section: "Caja",
    current: "Cobrar",
    actions: [{ label: "Registrar Cobro", icon: "", className: "" }],
    columns: ["#", "Cliente", "Documento", "Emision", "Vencimiento", "Saldo", "Acciones"],
    rows: [["1", "CLIENTES VARIOS", "-", "-", "-", "0.00", ""]],
    formFields: ["Cliente", "Documento", "Fecha", "Monto", "Medio de Pago", "Observacion"],
  },
  "/pagar": {
    title: "Cuentas por Pagar",
    section: "Caja",
    current: "Pagar",
    actions: [{ label: "Registrar Pago", icon: "", className: "" }],
    columns: ["#", "Proveedor", "Documento", "Emision", "Vencimiento", "Saldo", "Acciones"],
    rows: [["1", "-", "-", "-", "-", "0.00", ""]],
    formFields: ["Proveedor", "Documento", "Fecha", "Monto", "Medio de Pago", "Observacion"],
  },
  "/ingreso": {
    title: "Ingresos",
    section: "Caja",
    current: "Ingreso",
    actions: [{ label: "Nuevo Ingreso", icon: "", className: "" }],
    columns: ["#", "Fecha", "Concepto", "Medio", "Monto", "Acciones"],
    rows: [["1", "-", "-", "-", "0.00", ""]],
    formFields: ["Fecha", "Concepto", "Medio de Pago", "Monto", "Observacion"],
  },
  "/gasto": {
    title: "Gastos",
    section: "Caja",
    current: "Gasto",
    actions: [{ label: "Nuevo Gasto", icon: "", className: "" }],
    columns: ["#", "Fecha", "Concepto", "Medio", "Monto", "Acciones"],
    rows: [["1", "-", "-", "-", "0.00", ""]],
    formFields: ["Fecha", "Concepto", "Medio de Pago", "Monto", "Observacion"],
  },
  "/facturacion": {
    title: "Facturacion",
    section: "Facturacion",
    current: "Comprobantes no enviados",
    tabs: ["No enviado", "Rectificaciones", "Resumenes", "Anulaciones", "Validador"],
    tabRoutes: {
      "No enviado": "/facturacion",
      Rectificaciones: "/facturacion/rectificaciones",
      Resumenes: "/facturacion/resumenes",
      Anulaciones: "/facturacion/anulaciones",
      Validador: "/facturacion/validador",
    },
    actions: [{ label: "Enviar SUNAT", icon: "", className: "" }],
    columns: ["#", "Fecha", "Documento", "Cliente", "Total", "SUNAT", "Acciones"],
    rows: [["1", "-", "-", "-", "0.00", "Pendiente API", ""]],
    formFields: ["Fecha", "Documento", "Cliente", "Total", "Estado SUNAT", "Observacion"],
  },
  "/consulta": {
    title: "Consultas",
    section: "Consulta",
    current: "Consultas",
    actions: [{ label: "Buscar", icon: "", className: "" }],
    columns: ["#", "Tipo", "Descripcion", "Resultado", "Acciones"],
    rows: [["1", "-", "-", "Pendiente API", ""]],
    formFields: ["Tipo", "Descripcion", "Filtro", "Resultado"],
  },
  "/movimiento": {
    title: "Movimientos",
    section: "Almacen",
    current: "Movimiento",
    actions: [{ label: "Nuevo Movimiento", icon: "", className: "" }],
    columns: ["#", "Fecha", "Tipo", "Producto", "Cantidad", "Usuario", "Acciones"],
    rows: [["1", "-", "-", "-", "0", "-", ""]],
    formFields: ["Fecha", "Tipo", "Producto", "Cantidad", "Usuario", "Observacion"],
  },
  "/reporte": {
    title: "Reportes",
    section: "Reporte",
    current: "Reportes",
    tabs: ["Almacen", "Compras", "Ventas", "Caja", "Contable"],
    tabRoutes: {
      Almacen: "/reporte",
      Compras: "/reporte/compras",
      Ventas: "/reporte/ventas",
      Caja: "/reporte/caja",
      Contable: "/reporte/contable",
    },
    actions: [{ label: "Generar", icon: "", className: "" }],
    columns: ["Reporte", "Filtro", "Formato", "Acciones"],
    rows: [
      ["Productos", "Atributos", "PDF", ""],
      ["Ventas", "Fechas", "PDF/Excel", ""],
      ["Caja", "Medios", "PDF", ""],
    ],
    formFields: ["Reporte", "Fecha Inicio", "Fecha Fin", "Formato", "Filtro"],
  },
  "/empresa": {
    title: "Empresa",
    section: "Configuracion",
    current: "Empresa",
    actions: [{ label: "Editar Empresa", icon: "", className: "" }],
    columns: ["Campo", "Valor", "Estado"],
    rows: [
      ["Razon Social", "-", "Pendiente API"],
      ["RUC", "-", "Pendiente API"],
      ["Facturacion", "-", "Pendiente API"],
    ],
    formFields: ["Razon Social", "RUC", "Direccion", "Telefono", "Correo", "Facturacion"],
  },
  "/establecimiento": {
    title: "Establecimiento",
    section: "Configuracion",
    current: "Establecimiento",
    actions: [{ label: "Nuevo Establecimiento", icon: "", className: "" }],
    columns: ["#", "Descripcion", "Direccion", "Estado", "Acciones"],
    rows: [["1", "Principal", "-", "Activo", ""]],
    formFields: ["Descripcion", "Direccion", "Telefono", "Estado"],
  },
  "/serie": {
    title: "Serie de Comprobante",
    section: "Configuracion",
    current: "Serie",
    actions: [{ label: "Nueva Serie", icon: "", className: "" }],
    columns: ["#", "Comprobante", "Serie", "Numero", "Estado", "Acciones"],
    rows: [["1", "Boleta", "B001", "0", "Activo", ""]],
    formFields: ["Comprobante", "Serie", "Numero", "Estado"],
  },
  "/punto": {
    title: "Puntos",
    section: "Configuracion",
    current: "Puntos",
    actions: [{ label: "Configurar", icon: "", className: "" }],
    columns: ["Concepto", "Valor", "Estado"],
    rows: [["Valor por punto", "0.00", "Pendiente API"]],
    formFields: ["Concepto", "Valor", "Estado"],
  },
  "/transporte": {
    title: "Transporte",
    section: "Transporte",
    current: "Transportistas",
    actions: [{ label: "Nuevo Transporte", icon: "", className: "" }],
    columns: ["#", "Documento", "Nombre", "Placa", "Estado", "Acciones"],
    rows: [["1", "-", "-", "-", "Activo", ""]],
    formFields: ["Tipo Documento", "Documento", "Nombre", "Placa", "Licencia", "Estado"],
  },
  "/traslado": {
    title: "Traslado",
    section: "Almacen",
    current: "Traslado",
    actions: [{ label: "Nuevo Traslado", icon: "", className: "" }],
    columns: ["#", "Fecha", "Origen", "Destino", "Estado", "Acciones"],
    rows: [["1", "-", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha", "Origen", "Destino", "Producto", "Cantidad", "Estado"],
  },
  "/usuario": {
    title: "Usuarios",
    section: "Configuracion",
    current: "Usuarios",
    actions: [{ label: "Nuevo Usuario", icon: "", className: "" }],
    columns: ["#", "Usuario", "Nombres", "Tipo", "Estado", "Acciones"],
    rows: [["1", "admin", "Administrador", "admin", "Activo", ""]],
    formFields: ["Usuario", "Nombres", "Correo", "Tipo", "Establecimiento", "Estado"],
  },
  "/utilitario": {
    title: "Utilitarios",
    section: "Utilitario",
    current: "Herramientas",
    actions: defaultActions,
    columns: ["Herramienta", "Descripcion", "Estado", "Acciones"],
    rows: [["Datos bancarios", "Configuracion", "Pendiente API", ""]],
    formFields: ["Herramienta", "Descripcion", "Estado"],
  },
};

const extraModuleScreens: Record<string, ModuleScreen> = {
  "/caja/mpago": {
    title: "Medio Pago",
    section: "Caja",
    current: "Medio Pago",
    tabs: ["Arqueos", "Medios de Pago"],
    tabRoutes: {
      Arqueos: "/caja",
      "Medios de Pago": "/caja/mpago",
    },
    actions: [{ label: "Nuevo Medio Pago", icon: "", className: "", intent: "create" }],
    columns: ["#", "Descripcion", "Estado", "Acciones"],
    rows: [["1", "Efectivo", "Activo", ""]],
    formFields: ["Descripcion", "Estado"],
  },
  "/producto/inactivos": {
    title: "Productos Inactivos",
    section: "Almacen",
    current: "Inactivos",
    tabs: ["Activos", "Inactivos", "Stock vs Cantidad"],
    tabRoutes: {
      Activos: "/producto",
      Inactivos: "/producto/inactivos",
      "Stock vs Cantidad": "/producto/deficit",
    },
    actions: [{ label: "Activar Producto", icon: "", className: "", intent: "edit" }],
    columns: ["#", "Producto", "Laboratorio", "Stock", "P. Compra", "P. Venta", "Acciones"],
    rows: [["1", "-", "-", "0", "0.00", "0.00", ""]],
    formFields: ["Categoria", "Laboratorio", "Codigo Barra", "Descripcion", "Stock", "P. Compra", "P. Venta", "Estado"],
  },
  "/producto/deficit": {
    title: "Stock vs Cantidad",
    section: "Almacen",
    current: "Deficit",
    tabs: ["Activos", "Inactivos", "Stock vs Cantidad"],
    tabRoutes: {
      Activos: "/producto",
      Inactivos: "/producto/inactivos",
      "Stock vs Cantidad": "/producto/deficit",
    },
    actions: [{ label: "Buscar", icon: "", className: "", intent: "search" }],
    columns: ["#", "Producto", "Laboratorio", "Stock", "Cantidad Lote", "Diferencia", "Acciones"],
    rows: [["1", "-", "-", "0", "0", "0", ""]],
    formFields: ["Producto", "Laboratorio", "Stock", "Cantidad Lote", "Diferencia"],
  },
  "/facturacion/rectificaciones": {
    title: "Comprobante por Rectificar",
    section: "Facturacion",
    current: "Rectificaciones",
    tabs: ["No enviado", "Rectificaciones", "Resumenes", "Anulaciones", "Validador"],
    tabRoutes: {
      "No enviado": "/facturacion",
      Rectificaciones: "/facturacion/rectificaciones",
      Resumenes: "/facturacion/resumenes",
      Anulaciones: "/facturacion/anulaciones",
      Validador: "/facturacion/validador",
    },
    actions: [{ label: "Consultar CDR", icon: "", className: "", intent: "sync" }],
    columns: ["#", "Fecha", "Comprobante", "Numero", "Cliente", "Estado", "Acciones"],
    rows: [["1", "-", "-", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha Inicio", "Fecha Fin", "Comprobante", "Serie", "Numero", "Estado"],
  },
  "/facturacion/resumenes": {
    title: "Resumenes",
    section: "Facturacion",
    current: "Resumenes",
    tabs: ["No enviado", "Rectificaciones", "Resumenes", "Anulaciones", "Validador"],
    tabRoutes: {
      "No enviado": "/facturacion",
      Rectificaciones: "/facturacion/rectificaciones",
      Resumenes: "/facturacion/resumenes",
      Anulaciones: "/facturacion/anulaciones",
      Validador: "/facturacion/validador",
    },
    actions: [
      { label: "Nuevo Resumen", icon: "", className: "", intent: "create" },
      { label: "Enviar Resumen", icon: "", className: "", intent: "sync" },
    ],
    columns: ["#", "Fecha Emision", "Fecha Referencia", "Identificador", "Ticket", "Estado", "Acciones"],
    rows: [["1", "-", "-", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha Referencia", "Identificador", "Ticket", "Boletas", "Estado"],
  },
  "/facturacion/anulaciones": {
    title: "Anulaciones",
    section: "Facturacion",
    current: "Anulaciones",
    tabs: ["No enviado", "Rectificaciones", "Resumenes", "Anulaciones", "Validador"],
    tabRoutes: {
      "No enviado": "/facturacion",
      Rectificaciones: "/facturacion/rectificaciones",
      Resumenes: "/facturacion/resumenes",
      Anulaciones: "/facturacion/anulaciones",
      Validador: "/facturacion/validador",
    },
    actions: [
      { label: "Nueva Anulacion", icon: "", className: "", intent: "create" },
      { label: "Enviar Baja", icon: "", className: "", intent: "sync" },
    ],
    columns: ["#", "Fecha Emision", "Fecha Referencia", "Identificador", "Ticket", "Estado", "Acciones"],
    rows: [["1", "-", "-", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha Referencia", "Identificador", "Ticket", "Comprobantes", "Estado"],
  },
  "/facturacion/consistencia": {
    title: "Consistencia Documentos",
    section: "Facturacion",
    current: "Consistencia",
    tabs: ["No enviado", "Rectificaciones", "Resumenes", "Anulaciones", "Consistencia", "Validador"],
    tabRoutes: {
      "No enviado": "/facturacion",
      Rectificaciones: "/facturacion/rectificaciones",
      Resumenes: "/facturacion/resumenes",
      Anulaciones: "/facturacion/anulaciones",
      Consistencia: "/facturacion/consistencia",
      Validador: "/facturacion/validador",
    },
    actions: [{ label: "Buscar", icon: "", className: "", intent: "search" }],
    columns: ["#", "Fecha", "Comprobante", "Serie", "Numeracion", "Estado", "Acciones"],
    rows: [["1", "-", "-", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha Inicio", "Fecha Fin", "Comprobante", "Serie", "Estado"],
  },
  "/facturacion/validador": {
    title: "Validador Documentos",
    section: "Facturacion",
    current: "Validador",
    tabs: ["No enviado", "Rectificaciones", "Resumenes", "Anulaciones", "Consistencia", "Validador"],
    tabRoutes: {
      "No enviado": "/facturacion",
      Rectificaciones: "/facturacion/rectificaciones",
      Resumenes: "/facturacion/resumenes",
      Anulaciones: "/facturacion/anulaciones",
      Consistencia: "/facturacion/consistencia",
      Validador: "/facturacion/validador",
    },
    actions: [
      { label: "Validar", icon: "", className: "", intent: "sync" },
      { label: "Regularizar Documentos", icon: "", className: "", intent: "edit" },
    ],
    columns: ["#", "Fecha", "Comprobante", "Numero", "Cliente", "Estado Sunat", "Acciones"],
    rows: [["1", "-", "-", "-", "-", "Pendiente API", ""]],
    formFields: ["Fecha Inicio", "Fecha Fin", "Tipo", "Ticket", "Estado Sunat"],
  },
  "/reporte/ventas": {
    title: "Reporte de Ventas",
    section: "Reportes",
    current: "Ventas",
    tabs: ["Almacen", "Compras", "Ventas", "Caja", "Contable"],
    tabRoutes: {
      Almacen: "/reporte",
      Compras: "/reporte/compras",
      Ventas: "/reporte/ventas",
      Caja: "/reporte/caja",
      Contable: "/reporte/contable",
    },
    actions: [
      { label: "Imprimir", icon: "", className: "", intent: "print" },
      { label: "Excel", icon: "", className: "", intent: "export" },
    ],
    columns: ["Reporte", "Filtro", "Formato", "Acciones"],
    rows: [
      ["Ventas", "Fechas / usuario", "PDF", ""],
      ["Notas de venta", "Fechas / usuario", "PDF", ""],
      ["Producto vendido", "Producto / fechas", "PDF", ""],
      ["Cliente", "Cliente / fechas", "PDF", ""],
    ],
    formFields: ["Fecha Inicio", "Fecha Fin", "Usuario", "Producto", "Cliente", "Detallado"],
  },
  "/reporte/compras": {
    title: "Reporte de Compras",
    section: "Reportes",
    current: "Compras",
    tabs: ["Almacen", "Compras", "Ventas", "Caja", "Contable"],
    tabRoutes: {
      Almacen: "/reporte",
      Compras: "/reporte/compras",
      Ventas: "/reporte/ventas",
      Caja: "/reporte/caja",
      Contable: "/reporte/contable",
    },
    actions: [{ label: "Imprimir", icon: "", className: "", intent: "print" }],
    columns: ["Reporte", "Filtro", "Formato", "Acciones"],
    rows: [
      ["Compras", "Fechas", "PDF", ""],
      ["Producto comprado", "Producto / fechas", "PDF", ""],
      ["Proveedor", "Proveedor / fechas", "PDF", ""],
    ],
    formFields: ["Fecha Inicio", "Fecha Fin", "Proveedor", "Producto", "Detallado"],
  },
  "/reporte/caja": {
    title: "Reporte de Caja",
    section: "Reportes",
    current: "Caja",
    tabs: ["Almacen", "Compras", "Ventas", "Caja", "Contable"],
    tabRoutes: {
      Almacen: "/reporte",
      Compras: "/reporte/compras",
      Ventas: "/reporte/ventas",
      Caja: "/reporte/caja",
      Contable: "/reporte/contable",
    },
    actions: [{ label: "Imprimir", icon: "", className: "", intent: "print" }],
    columns: ["Reporte", "Filtro", "Formato", "Acciones"],
    rows: [
      ["Medios de pago", "Fechas", "PDF", ""],
      ["Medios por usuario", "Fechas / usuario", "PDF", ""],
    ],
    formFields: ["Fecha Inicio", "Fecha Fin", "Usuario"],
  },
  "/reporte/contable": {
    title: "Registros Contables",
    section: "Reportes",
    current: "Contable",
    tabs: ["Almacen", "Compras", "Ventas", "Caja", "Contable"],
    tabRoutes: {
      Almacen: "/reporte",
      Compras: "/reporte/compras",
      Ventas: "/reporte/ventas",
      Caja: "/reporte/caja",
      Contable: "/reporte/contable",
    },
    actions: [{ label: "Descargar", icon: "", className: "", intent: "export" }],
    columns: ["Registro", "Periodo", "Formato", "Acciones"],
    rows: [
      ["Compras", "Mes / ano", "Excel", ""],
      ["Ventas", "Mes / ano", "Excel", ""],
      ["Directorio", "Mes / ano", "TXT", ""],
    ],
    formFields: ["Ano", "Mes", "Formato"],
  },
  "/consulta/stockv": {
    title: "Stock Valorizado",
    section: "Consultas",
    current: "Stock Valorizado",
    actions: [{ label: "Buscar", icon: "", className: "", intent: "search" }],
    columns: ["#", "Codigo", "Producto", "Stock", "Costo Prom.", "Total", "Acciones"],
    rows: [["1", "-", "-", "0", "0.00", "0.00", ""]],
    formFields: ["Producto", "Fecha Inicio", "Fecha Fin"],
  },
  "/consulta/kardex": {
    title: "Kardex",
    section: "Consultas",
    current: "Kardex",
    actions: [{ label: "Buscar", icon: "", className: "", intent: "search" }],
    columns: ["Fecha y hora", "Tipo transaccion", "Numero", "Entrada", "Salida", "Saldo", "Costo"],
    rows: [["-", "-", "-", "0", "0", "0", "0.00"]],
    formFields: ["Producto", "Fecha Inicio", "Fecha Fin"],
  },
  "/consulta/vhorario": {
    title: "Ventas Horario",
    section: "Consultas",
    current: "Ventas Horario",
    actions: [{ label: "Buscar", icon: "", className: "", intent: "search" }],
    columns: ["Hora", "Cantidad", "Total Ventas", "Total Costo Prom.", "Utilidad", "Acciones"],
    rows: [["-", "0", "0.00", "0.00", "0.00", ""]],
    formFields: ["Fecha Inicio", "Fecha Fin", "Hora Inicio", "Hora Fin"],
  },
  "/consulta/bvendedor": {
    title: "Bonificaciones Vendedor",
    section: "Consultas",
    current: "Bonificaciones",
    actions: [{ label: "Buscar", icon: "", className: "", intent: "search" }],
    columns: ["COD", "Producto", "Bonif", "Vendidos", "Importe", "Acciones"],
    rows: [["-", "-", "0", "0", "0.00", ""]],
    formFields: ["Ano", "Mes", "Usuario"],
  },
  "/empresa/facturacion": {
    title: "Empresa Facturacion",
    section: "Configuracion",
    current: "Facturacion",
    actions: [{ label: "Guardar", icon: "", className: "", intent: "edit" }],
    columns: ["Campo", "Valor", "Estado"],
    rows: [["SOAP", "-", "Pendiente API"], ["Certificado", "-", "Pendiente API"]],
    formFields: ["SOAP", "Usuario", "Secundario", "Certificado", "Clave", "Vencimiento"],
  },
  "/empresa/avanzado": {
    title: "Empresa Avanzado",
    section: "Configuracion",
    current: "Avanzado",
    actions: [{ label: "Guardar", icon: "", className: "", intent: "edit" }],
    columns: ["Opcion", "Valor", "Estado"],
    rows: [["Compra", "-", "Pendiente API"], ["Venta", "-", "Pendiente API"], ["Arqueo", "-", "Pendiente API"]],
    formFields: ["Compra", "Venta", "Arqueo", "Predeterminar Establecimiento", "Producto", "Descuento"],
  },
  "/transporte/publico": {
    title: "Transporte Publico",
    section: "Configuracion",
    current: "Transporte Publico",
    actions: [{ label: "Nuevo T. Publico", icon: "", className: "", intent: "create" }],
    columns: ["#", "Documento", "Nombre", "Estado", "Acciones"],
    rows: [["1", "-", "-", "Activo", ""]],
    formFields: ["Tipo Documento", "Documento", "Nombre", "Estado"],
  },
};

export function getModuleScreen(href: string, fallbackTitle: string): ModuleScreen {
  return (
    extraModuleScreens[href] ??
    moduleScreens[href] ?? {
      title: fallbackTitle,
      section: "Modulo",
      current: fallbackTitle,
      actions: defaultActions,
      columns: ["#", "Descripcion", "Estado", "Acciones"],
      rows: [["1", fallbackTitle, "Pendiente API", ""]],
      formFields: ["Descripcion", "Estado"],
    }
  );
}
