"use client";

import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PageHeader } from "@/components/ui/page-header";
import { useSession } from "@/features/auth/context/session-context";
import { apiRequest } from "@/features/shared/api/client";
import { apiErrorMessage } from "@/features/shared/api/error-message";
import { apiEndpoints } from "@/features/shared/api/endpoints";
import type { ApiPage } from "@/features/shared/api/types";
import type { DataTableColumn } from "@/features/shared/ui/data-table/data-table";
import { DataTable } from "@/features/shared/ui/data-table/data-table";
import { Modal } from "@/features/shared/ui/modal/modal";
import { useToast } from "@/features/shared/ui/toast/toast-provider";

type CashSession = { id: string; register: string; register_name: string; opened_by_name: string; status: string; opening_amount: string; expected_cash: string; counted_cash: string | null; difference: string | null; opened_at: string; closed_at: string | null };
type CashCount = { id: string; expected_breakdown: Record<string, string>; expected_cash: string; counted_cash: string; difference: string; count_type: string };
type CashRegister = { id: string; branch: string; name: string; is_active: boolean };
function message(error: unknown) { return apiErrorMessage(error, "No se pudo procesar la caja."); }

export function CashOperationsPage() {
  const { activeBranchId } = useSession(); const { showToast } = useToast(); const queryClient = useQueryClient();
  const [mode, setMode] = useState<"open" | "count" | "close" | null>(null); const [session, setSession] = useState<CashSession | null>(null); const [countResult, setCountResult] = useState<CashCount | null>(null);
  const [opening, setOpening] = useState({ register: "", opening_amount: "0", notes: "" });
  const [count, setCount] = useState({ count_type: "PARTIAL", counted_cash: "", observation: "" });
  const sessionsQuery = useQuery({ queryKey: ["cash-sessions"], queryFn: () => apiRequest<ApiPage<CashSession>>(apiEndpoints.cashSessions, { query: { pageSize: 100, ordering: "-opened_at" } }) });
  const registersQuery = useQuery({ queryKey: ["cash-registers", activeBranchId], queryFn: () => apiRequest<ApiPage<CashRegister>>(apiEndpoints.cashRegisters, { query: { pageSize: 100, branch: activeBranchId, is_active: true } }), enabled: Boolean(activeBranchId) });
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["cash-sessions"] }), queryClient.invalidateQueries({ queryKey: ["cash-registers"] })]);
  const openMutation = useMutation({ mutationFn: () => apiRequest(`${apiEndpoints.cashRegisters}open/`, { method: "POST", body: opening }), onSuccess: refresh });
  const countMutation = useMutation({ mutationFn: () => apiRequest<CashCount>(`${apiEndpoints.cashSessions}${session?.id}/counts/`, { method: "POST", body: count }), onSuccess: refresh });
  const closeMutation = useMutation({ mutationFn: () => apiRequest(`${apiEndpoints.cashSessions}${session?.id}/close/`, { method: "POST", body: { counted_cash: count.counted_cash, notes: count.observation } }), onSuccess: refresh });
  const activeRegisters = registersQuery.data?.items ?? [];
  async function submit(event: FormEvent) { event.preventDefault(); try { if (mode === "open") { await openMutation.mutateAsync(); showToast({ tone: "success", title: "Caja abierta" }); setMode(null); } else if (mode === "count") { const result = await countMutation.mutateAsync(); setCountResult(result); showToast({ tone: "success", title: "Arqueo registrado" }); } else { await closeMutation.mutateAsync(); showToast({ tone: "success", title: "Caja cerrada" }); setMode(null); setSession(null); } } catch (error) { showToast({ tone: "error", title: "Operacion rechazada", description: message(error) }); } }
  const columns = useMemo<DataTableColumn<CashSession>[]>(() => [
    { id: "register", header: "Caja", value: (row) => row.register_name }, { id: "opened", header: "Apertura", value: (row) => new Date(row.opened_at).toLocaleString("es-PE"), sortable: true }, { id: "user", header: "Usuario", value: (row) => row.opened_by_name }, { id: "initial", header: "Inicial", value: (row) => `S/ ${Number(row.opening_amount).toFixed(2)}` }, { id: "expected", header: "Efectivo esperado", value: (row) => `S/ ${Number(row.expected_cash).toFixed(2)}` }, { id: "status", header: "Estado", value: (row) => row.status }, { id: "actions", header: "Acciones", render: (row) => row.status === "OPEN" ? <div className="row-actions"><button type="button" className="ghost-button compact-button" onClick={() => { setSession(row); setCount({ count_type: "PARTIAL", counted_cash: row.expected_cash, observation: "" }); setCountResult(null); setMode("count"); }}><i className="fa fa-calculator" /> Arquear</button><button type="button" className="app-button primary compact-button" onClick={() => { setSession(row); setCount({ count_type: "FINAL", counted_cash: row.expected_cash, observation: "" }); setMode("close"); }}><i className="fa fa-lock" /> Cerrar</button></div> : null },
  ], []);
  const busy = openMutation.isPending || countMutation.isPending || closeMutation.isPending;
  return <><PageHeader title="Caja actual y arqueos" section="Caja y finanzas" current="Caja" actions={<button type="button" className="app-button primary" onClick={() => setMode("open")}><i className="fa fa-lock-open" /> Abrir caja</button>} /><section className="content-panel"><DataTable rows={sessionsQuery.data?.items ?? []} columns={columns} rowKey={(row) => row.id} loading={sessionsQuery.isLoading} error={sessionsQuery.error ? message(sessionsQuery.error) : undefined} onRetry={() => void sessionsQuery.refetch()} /></section><Modal open={mode !== null} title={mode === "open" ? "Apertura de caja" : mode === "count" ? "Arqueo de caja" : "Cierre de caja"} busy={busy} onClose={() => setMode(null)} footer={<><button type="button" className="ghost-button" onClick={() => setMode(null)}>Cancelar</button><button type="submit" form="cash-operation-form" className="app-button primary" disabled={busy}>{busy ? "Procesando..." : "Confirmar"}</button></>}><form id="cash-operation-form" className="form-grid" onSubmit={(event) => void submit(event)}>{mode === "open" ? <><label><span>Caja</span><select required value={opening.register} onChange={(e) => setOpening({ ...opening, register: e.target.value })}><option value="">Seleccionar</option>{activeRegisters.map((register) => <option value={register.id} key={register.id}>{register.name}</option>)}</select></label><label><span>Monto inicial</span><input type="number" min="0" step="0.01" required value={opening.opening_amount} onChange={(e) => setOpening({ ...opening, opening_amount: e.target.value })} /></label><label className="form-span-full"><span>Observacion</span><textarea value={opening.notes} onChange={(e) => setOpening({ ...opening, notes: e.target.value })} /></label></> : <><div className="cash-expected"><span>Efectivo esperado</span><strong>S/ {Number(session?.expected_cash ?? 0).toFixed(2)}</strong></div>{mode === "count" ? <label><span>Tipo de arqueo</span><select value={count.count_type} onChange={(e) => setCount({ ...count, count_type: e.target.value })}><option value="PARTIAL">Parcial</option><option value="FINAL">Final</option></select></label> : null}<label><span>Efectivo contado</span><input type="number" min="0" step="0.01" required value={count.counted_cash} onChange={(e) => setCount({ ...count, counted_cash: e.target.value })} /></label><label className="form-span-full"><span>Observacion</span><textarea value={count.observation} onChange={(e) => setCount({ ...count, observation: e.target.value })} /></label>{countResult ? <div className="cash-count-result form-span-full"><strong>Diferencia: S/ {Number(countResult.difference).toFixed(2)}</strong>{Object.entries(countResult.expected_breakdown).map(([key, value]) => <span key={key}>{key}: S/ {Number(value).toFixed(2)}</span>)}</div> : null}</>}</form></Modal></>;
}
