# Generated by Django 6.0.6 on 2026-06-20 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_alter_cashmovement_movement_type_cashcount'),
        ('catalog', '0002_activeingredient_productwarehouselocation_and_more'),
        ('purchases', '0001_initial'),
        ('sales', '0002_sale_amount_paid_sale_balance_due_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_type', models.CharField(choices=[('EXPENSE', 'Gasto'), ('INCOME', 'Ingreso')], max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=8)),
                ('origin', models.CharField(choices=[('SALE', 'Venta'), ('RECEIVABLE_COLLECTION', 'Cobro CxC'), ('PAYABLE_PAYMENT', 'Pago CxP'), ('EXPENSE', 'Gasto'), ('ADDITIONAL_INCOME', 'Ingreso adicional'), ('CASH_WITHDRAWAL', 'Retiro de caja'), ('CASH_CONTRIBUTION', 'Aporte de caja'), ('ADJUSTMENT', 'Ajuste')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=16)),
                ('beneficiary_or_source', models.CharField(blank=True, max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('VOID', 'Anulado')], default='ACTIVE', max_length=16)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=240)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='tenancy.branch')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='cash.cashsession')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.financialcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements_created', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayableAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_created', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='purchases.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='catalog.supplier')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayablePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=16)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('operation_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.payableaccount')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cashsession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='catalog.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receivable', to='sales.sale')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=16)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('operation_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='finance.receivableaccount')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cashsession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('company', 'category_type', 'name'), name='uq_financial_category_company_type_name'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['company', 'branch', 'date'], name='finance_fin_company_a38c18_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['company', 'origin', 'source_type', 'source_id'], name='finance_fin_company_1795bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_financial_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='payableaccount',
            index=models.Index(fields=['company', 'branch', 'status', 'due_date'], name='finance_pay_company_68c8aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='payableaccount',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='ck_payable_original_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='payableaccount',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='ck_payable_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payableaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ck_payable_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payablepayment',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_payable_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='payablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payable_payment_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='receivableaccount',
            index=models.Index(fields=['company', 'branch', 'status', 'due_date'], name='finance_rec_company_7d1e3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivableaccount',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='ck_receivable_original_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='receivableaccount',
            constraint=models.CheckConstraint(condition=models.Q(('collected_amount__gte', 0)), name='ck_receivable_collected_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receivableaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ck_receivable_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receivablecollection',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_receivable_collection_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='receivablecollection',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_receivable_collection_gt_zero'),
        ),
    ]
