# Generated by Django 6.0.6 on 2026-06-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='attachment',
            field=models.FileField(blank=True, upload_to='finance/%Y/%m/'),
        ),
    ]
