# Generated by Django 6.0.6 on 2026-06-20 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(default='DNI', max_length=16)),
                ('document_number', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
            options={
                'verbose_name_plural': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_code', models.CharField(max_length=48)),
                ('commercial_name', models.CharField(max_length=220)),
                ('active_ingredient', models.CharField(blank=True, max_length=220)),
                ('product_type', models.CharField(choices=[('MEDICINE', 'Medicamento'), ('SUPPLY', 'Insumo'), ('SERVICE', 'Servicio')], max_length=16)),
                ('requires_lot', models.BooleanField(default=True)),
                ('requires_expiry', models.BooleanField(default=True)),
                ('is_controlled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=48)),
                ('presentation', models.CharField(max_length=120)),
                ('unit_of_measure', models.CharField(max_length=32)),
                ('sale_unit', models.CharField(max_length=32)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('allows_fractioning', models.BooleanField(default=False)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('base_sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(default='RUC', max_length=16)),
                ('document_number', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_category_company_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'full_name'], name='catalog_cus_company_4a3183_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('company', 'document_number'), name='uq_customer_company_document'),
        ),
        migrations.AddConstraint(
            model_name='laboratory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_laboratory_company_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'commercial_name', 'is_active'], name='catalog_pro_company_010e4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'internal_code'), name='uq_product_company_internal_code'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['company', 'product', 'is_active'], name='catalog_pro_company_eaa4f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='uq_variant_company_sku'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_barcode_company_code'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'legal_name'], name='catalog_sup_company_c04127_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'document_number'), name='uq_supplier_company_document'),
        ),
    ]
