# Generated by Django 6.0.6 on 2026-06-20 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_active_ingredients(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ActiveIngredient = apps.get_model("catalog", "ActiveIngredient")
    for product in Product.objects.exclude(active_ingredient_text="").iterator():
        name = product.active_ingredient_text.strip()
        if not name:
            continue
        ingredient, _ = ActiveIngredient.objects.get_or_create(company_id=product.company_id, name=name)
        product.active_ingredient_id = ingredient.id
        product.save(update_fields=["active_ingredient"])


def restore_active_ingredient_text(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.select_related("active_ingredient").exclude(active_ingredient=None).iterator():
        product.active_ingredient_text = product.active_ingredient.name
        product.save(update_fields=["active_ingredient_text"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWarehouseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('aisle', models.CharField(blank=True, max_length=48)),
                ('shelf', models.CharField(blank=True, max_length=48)),
                ('level', models.CharField(blank=True, max_length=48)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digemid_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='earns_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sanitary_registration',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_affectation',
            field=models.CharField(choices=[('TAXED', 'Gravado'), ('EXEMPT', 'Exonerado'), ('UNAFFECTED', 'Inafecto')], default='TAXED', max_length=16),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='currency',
            field=models.CharField(default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_pack_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit_purchase_cost',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_factor__gt', 0)), name='ck_variant_purchase_factor_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_pack_price__gte', 0)), name='ck_variant_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('base_sale_price__gt', 0)), name='ck_variant_sale_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sale_factor__gt', 0)), name='ck_variant_sale_factor_gt_zero'),
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='active_ingredient',
            new_name='active_ingredient_text',
        ),
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.activeingredient'),
        ),
        migrations.RunPython(migrate_active_ingredients, restore_active_ingredient_text),
        migrations.RemoveField(
            model_name='product',
            name='active_ingredient_text',
        ),
        migrations.AddField(
            model_name='productwarehouselocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='productwarehouselocation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_locations', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='productwarehouselocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_locations', to='tenancy.warehouse'),
        ),
        migrations.AddField(
            model_name='therapeuticaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='therapeutic_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.therapeuticaction'),
        ),
        migrations.AddConstraint(
            model_name='activeingredient',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_active_ingredient_company_name'),
        ),
        migrations.AddIndex(
            model_name='productwarehouselocation',
            index=models.Index(fields=['company', 'warehouse', 'is_active'], name='catalog_pro_company_b372b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productwarehouselocation',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'variant'), name='uq_product_location_warehouse_variant'),
        ),
        migrations.AddConstraint(
            model_name='productwarehouselocation',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'code'), name='uq_product_location_warehouse_code'),
        ),
        migrations.AddConstraint(
            model_name='therapeuticaction',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_therapeutic_action_company_name'),
        ),
    ]
