# Generated by Django 6.0.6 on 2026-06-20 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_activeingredient_productwarehouselocation_and_more'),
        ('inventory', '0001_initial'),
        ('sales', '0002_sale_amount_paid_sale_balance_due_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('contact_phone', models.CharField(max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('STORE_PICKUP', 'Recojo en tienda'), ('SCHEDULED_DELIVERY', 'Entrega programada')], max_length=32)),
                ('delivery_address', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PREPARED', 'Preparada'), ('PARTIALLY_FULFILLED', 'Parcialmente atendida'), ('FULFILLED', 'Atendida'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Vencida')], default='DRAFT', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('converted_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_request', to='sales.sale')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_requests', to='catalog.customer')),
            ],
            options={
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('authorized_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('preferred_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lot')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_requests.customerrequest')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['company', 'branch', 'status', 'scheduled_at'], name='customer_re_company_4371dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerrequest',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_customer_request_code'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_customer_request_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('reference_price__gte', 0)), name='ck_customer_request_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('authorized_discount__gte', 0)), name='ck_customer_request_discount_non_negative'),
        ),
    ]
