# Generated by Django 6.0.6 on 2026-06-20 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSING', 'En cierre'), ('CLOSED', 'Cerrada'), ('CLOSED_WITH_DIFFERENCE', 'Cerrada con diferencia')], default='OPEN', max_length=32)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_openings', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cash.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Apertura'), ('CASH_SALE', 'Venta en efectivo'), ('MANUAL_IN', 'Ingreso manual'), ('WITHDRAWAL', 'Retiro'), ('REFUND', 'Devolucion')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reference_type', models.CharField(blank=True, max_length=60)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(max_length=240)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cash.cashsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_cash_register_company_code'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['company', 'status', 'opened_at'], name='cash_cashse_company_b2ad11_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSING'])), fields=('register',), name='uq_cash_register_active_session'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['company', 'session', 'created_at'], name='cash_cashmo_company_ea2d4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_cash_movement_amount_gt_zero'),
        ),
    ]
