# Generated by Django 6.0.6 on 2026-06-20 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Apertura'), ('CASH_SALE', 'Venta en efectivo'), ('MANUAL_IN', 'Ingreso manual'), ('WITHDRAWAL', 'Retiro'), ('REFUND', 'Devolucion'), ('RECEIVABLE_COLLECTION', 'Cobro de cuenta'), ('PAYABLE_PAYMENT', 'Pago de cuenta'), ('EXPENSE', 'Gasto'), ('ADDITIONAL_INCOME', 'Ingreso adicional'), ('CONTRIBUTION', 'Aporte de caja')], max_length=24),
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_type', models.CharField(choices=[('PARTIAL', 'Parcial'), ('FINAL', 'Final')], max_length=16)),
                ('expected_breakdown', models.JSONField(default=dict)),
                ('counted_breakdown', models.JSONField(default=dict)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=16)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=16)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=16)),
                ('observation', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='cash.cashsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'session', 'created_at'], name='cash_cashco_company_edeb53_idx')],
            },
        ),
    ]
