# Generated by Django 6.0.6 on 2026-06-20 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('CANCELLED', 'Anulada')], default='COMPLETED', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('change_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('sold_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tenancy.branch')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cash.cashsession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalog.customer')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tenancy.posterminal')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tenancy.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=24)),
                ('prefix', models.CharField(max_length=12)),
                ('current_number', models.PositiveBigIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'branch', 'document_type'), name='uq_sequence_company_branch_type')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'branch', 'sold_at', 'status'], name='sales_sale_company_48dee8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uq_sale_company_number'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_sale_company_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_sale_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_sale_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_sale_payment_gt_zero'),
        ),
    ]
