# Generated by Django 6.0.6 on 2026-06-20 23:59

from django.db import migrations, models


def initialize_paid_sales(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    for sale in Sale.objects.all().iterator():
        sale.amount_paid = sale.total
        sale.balance_due = 0
        sale.save(update_fields=["amount_paid", "balance_due"])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_condition',
            field=models.CharField(choices=[('CASH', 'Contado'), ('CREDIT', 'Credito')], default='CASH', max_length=16),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(initialize_paid_sales, migrations.RunPython.noop),
    ]
