# Generated by Django 6.0.8 on 2026-08-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_tax_and_discount_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
